apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: dss-kv-encrypt-sys                # The name of the Azure key vault
  namespace: kube-system
spec:
  provider: azure
  parameters:
    keyvaultName: dss-kv-encrypt # The name of the Azure key vault
    useVMManagedIdentity: "true"
    usePodIdentity: "false"         
    userAssignedIdentityID: 52506966-7a91-4cb3-aeba-e13069b81cc6 
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: admin      # In this example, 'ExampleSecret'   
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: 7bc20dae-08c5-4604-91da-e13a0980fa02               # The tenant ID containing the Azure Key Vault instance
