apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: dss-kv-encrypt-sys
spec:
  provider: azure
  parameters:
    keyvaultName: dss-kv-encrypt
    useVMManagedIdentity: "true"
    usePodIdentity: "false"         
    userAssignedIdentityID: 52506966-7a91-4cb3-aeba-e13069b81cc6 
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: secrets-store1   
          objectType: secret              
          objectAlias: my-db-pwd
        - |
          objectName: secrets-store1
          objectType: secret
          objectAlias: my-secrets
        - |
          objectName: csi-key
          objectType: key
          objectAlias: encryption-key
    tenantId: 7bc20dae-08c5-4604-91da-e13a0980fa02 
